### ISSUE TITLE
Incomplete secret value passed to container if secret contains "=="

### ISSUE THREAD

**Issue by ramit-rulz** [mikesir87/docker-secrets-simulator#2]
If secret value contains "==", only the substring before the "==" is passed to the container (in /run/secrets). 

For example, if my secret value is "crazy_long==connection_string", then only crazy_long is passed to the container as secret value.
Example docker-compose:

> `version: '3.2'

> services:
>   secret-simulator:
>     image: mikesir87/secrets-simulator
>     volumes:
>       - secrets:/run/secrets:rw
>     environment:
>       - MONGO_CONNECTION="crazylong==connectionstring"
>   myapp:
>     image: xxx
>     volumes:
>       - secrets:/run/secrets:ro
> volumes:
>   secrets:
>     driver: local`

**Comment by Blacksmoke16** [comment]
Can confirm.  This is especially a pain when dealing with Base64 encoded values as `==` is used for padding.
